In [2]:
import numpy as np

np.__version__

'1.19.5'

In [8]:
a = np.array([1, 2, 3, 4, 5])

a.shape
a.dtype
a.ndim
a.size
a.itemsize

4

In [11]:
b = a * np.array([2, 3, 4, 5, 6])
b.sum()

70

In [12]:
l = [1, 2, 3]
a = np.array(l)
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [22]:
a = np.array([1, 2, 3])
a2 = np.sqrt(a)
a2

array([1.        , 1.41421356, 1.73205081])

In [23]:
# Dot Product

a = np.array([1, 2])
b = np.array([3, 4])

dot = np.dot(a, b)
dot

# or a @ b for dot product

11

In [27]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a, b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

print('Time with lists:', t1)
print('Time with array:', t2)
print('Ratio', t1/t2)

Time with lists: 0.479791500000033
Time with array: 0.0026289999999562497
Ratio 182.49961963028431


In [46]:
a = np.array([[1, 2], [3, 4]])
# print('Shape: ', a.shape)

print(a[:,0]) # prva kolona
print(a[0,:]) # prvi red

a.T

[1 3]
[1 2]


array([[1, 3],
       [2, 4]])

In [49]:
det = np.linalg.det(a) # determinant
diag = np.diag(a)


array([1, 4])

In [58]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[:2, 1:3]
a[-1, -1]

12

In [88]:
# Reshaping

a = np.arange(1, 7)
b = a.reshape(2, 3)
c = a.reshape(3, 2)
d = np.concatenate((a, b), axis=None)
print(d)
f = np.random.choice(7, size=10)
g = np.random.choice([1,2,3,4], size=8)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [89]:
# Copying

a = np.array([1,2,3])
b = a # only copies reference!
b[0] = 42
print(a)

a = np.array([1,2,3])
b = a.copy() # actual copy
b[0] = 42
print(a)

[42  2  3]
[1 2 3]


In [99]:
# Generating Arrays

a = np.zeros((2, 3))
b = np.ones((2, 3))
c = np.full((3, 3), 5)
d = np.eye(3)
e = np.arange(10)
f = np.linspace(0, 10, 5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [87]:
# Random Numbers

a = np.random.random((3, 2))
b = np.random.randn(3, 2)
c = np.random.randint(3, 10, size=(3, 3))
c

array([[5, 4, 3],
       [4, 3, 5],
       [7, 7, 7]])

In [76]:
# Eigenvalues

a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [73]:
# Solve Linear Systems

# x1 + x2 = 2200
# 1.5 x1 + 4 x2 = 5050

A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200,5050])

x = np.linalg.solve(A, b)
print(x)

[1500.  700.]
[1500.  700.]


In [ ]:
# Loading CSV files
data = np.loadtxt('filename.csv', delimiter=',', dtype=np.float32)